In [1]:
import tensorflow as tf
pred = tf.nn.softmax([0.,1.,2.,3.,4.,5.,6.])
sess = tf.Session()  
print(sess.run(pred)) 
# 一、tensorflow 如果直接打印pred，返回的是对象，无法显示对象内容
# tf.nn.softmax(logits,axis=None,name=None,dim=None)
# 输入: 全连接层（往往是模型的最后一层）的值， 输出: 归一化的值，含义是属于该位置的概率;

[0.0015683  0.00426308 0.01158826 0.03150015 0.0856263  0.23275642
 0.6326975 ]


In [2]:
x = tf.constant([[1, 2, 2], [0, 1, 1]])
sess = tf.Session() 
print(sess.run(tf.reduce_sum(x))) # 6 默认值为None,则缩小所有尺寸.
print(sess.run(tf.reduce_mean(x))) # 6 默认值为None,则缩小所有尺寸.

7
1


In [3]:
import numpy as np
a = np.array([[2, 4, 6, 1], [1, 5, 2, 9]])
print(a.shape)
print(np.argmax(a))
print(np.argmax(a, axis=0))  #竖着比较，返回行号
print(np.argmax(a, axis=1))  #横着比较，返回列号

(2, 4)
7
[0 1 0 1]
[2 3]


In [4]:
a = np.array([0,1,2,3,4])
b = np.array([5,6,7,8,9])
# 注意一下顺序，a和b是跟随着，随机打乱
state = np.random.get_state()
np.random.shuffle(a)
np.random.set_state(state)
np.random.shuffle(b)
print(a)
print(b)

[4 2 1 3 0]
[9 7 6 8 5]


In [5]:
m = np.array([0,1,2,0,4])
# 多维数组禁用
each_type_index= np.where(m == 0)[0]
print(each_type_index)
print(m[each_type_index])

[0 3]
[0 0]


In [ ]:
# 笔记
1、tensorflow 需要打印tensor，需要使用sess.run(pred)，否则打印是对象
2、mnist数据集要to one hot
3、输入图片需要打乱数据